//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyEights.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrazyEights.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar a la sala.
        /// </summary>
        public static string btnAccederComoInvitado {
            get {
                return ResourceManager.GetString("btnAccederComoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        public static string btnCambiarContraseña {
            get {
                return ResourceManager.GetString("btnCambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartas clásicas.
        /// </summary>
        public static string btnCartasClasicas {
            get {
                return ResourceManager.GetString("btnCartasClasicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartas minimalistas.
        /// </summary>
        public static string btnCartasMinimalistas {
            get {
                return ResourceManager.GetString("btnCartasMinimalistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string btnCerrarSesionDeJuego {
            get {
                return ResourceManager.GetString("btnCerrarSesionDeJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear partida.
        /// </summary>
        public static string btnCrearPartida {
            get {
                return ResourceManager.GetString("btnCrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        public static string btnEditarContraseña {
            get {
                return ResourceManager.GetString("btnEditarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontrar partida.
        /// </summary>
        public static string btnEncontrarPartida {
            get {
                return ResourceManager.GetString("btnEncontrarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar cambios.
        /// </summary>
        public static string btnGuardarCambiosDePerfil {
            get {
                return ResourceManager.GetString("btnGuardarCambiosDePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string btnIniciarSesion {
            get {
                return ResourceManager.GetString("btnIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar como Invitado.
        /// </summary>
        public static string btnJugarComoInvitado {
            get {
                return ResourceManager.GetString("btnJugarComoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar Contraseña.
        /// </summary>
        public static string btnRecuperarContraseña {
            get {
                return ResourceManager.GetString("btnRecuperarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string btnRegistrarse {
            get {
                return ResourceManager.GetString("btnRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir del juego.
        /// </summary>
        public static string btnSalirDelJuego {
            get {
                return ResourceManager.GetString("btnSalirDelJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienda.
        /// </summary>
        public static string btnTienda {
            get {
                return ResourceManager.GetString("btnTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese una contraseña válida..
        /// </summary>
        public static string lbAdvertenciaContraseñaInvalida {
            get {
                return ResourceManager.GetString("lbAdvertenciaContraseñaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese un correo electrónico válido..
        /// </summary>
        public static string lbAdvertenciaCorreoElectronicoInvalido {
            get {
                return ResourceManager.GetString("lbAdvertenciaCorreoElectronicoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string lbAmigosMenuPrincipal {
            get {
                return ResourceManager.GetString("lbAmigosMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ya tienes una cuenta?.
        /// </summary>
        public static string lbApoyoIniciarSesion {
            get {
                return ResourceManager.GetString("lbApoyoIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Te están esperando en una sala?.
        /// </summary>
        public static string lbApoyoJugarComoInvitado {
            get {
                return ResourceManager.GetString("lbApoyoJugarComoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string lbApoyoRecuperarContraseña {
            get {
                return ResourceManager.GetString("lbApoyoRecuperarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tienes una cuenta?.
        /// </summary>
        public static string lbApoyoRegistrarse {
            get {
                return ResourceManager.GetString("lbApoyoRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string lbAyudaMenuPrincipal {
            get {
                return ResourceManager.GetString("lbAyudaMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar nombre de usuario.
        /// </summary>
        public static string lbCambiarNombreDeUsuario {
            get {
                return ResourceManager.GetString("lbCambiarNombreDeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe de completar todos los campos.
        /// </summary>
        public static string lbCamposVacios {
            get {
                return ResourceManager.GetString("lbCamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string lbCerrarVentana {
            get {
                return ResourceManager.GetString("lbCerrarVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de sala:.
        /// </summary>
        public static string lbCodigoSala {
            get {
                return ResourceManager.GetString("lbCodigoSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string lbConfiguracion {
            get {
                return ResourceManager.GetString("lbConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar nueva contraseña:.
        /// </summary>
        public static string lbConfirmarNuevaContraseña {
            get {
                return ResourceManager.GetString("lbConfirmarNuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        public static string lbContraseña {
            get {
                return ResourceManager.GetString("lbContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual:.
        /// </summary>
        public static string lbContraseñaActual {
            get {
                return ResourceManager.GetString("lbContraseñaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual es incorrecta.
        /// </summary>
        public static string lbContraseñaActualInvalida {
            get {
                return ResourceManager.GetString("lbContraseñaActualInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico:.
        /// </summary>
        public static string lbCorreoElectronico {
            get {
                return ResourceManager.GetString("lbCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string lbIdioma {
            get {
                return ResourceManager.GetString("lbIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misiones.
        /// </summary>
        public static string lbMisionesMenuPrincipal {
            get {
                return ResourceManager.GetString("lbMisionesMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de jugador.
        /// </summary>
        public static string lbNombreDeJugador {
            get {
                return ResourceManager.GetString("lbNombreDeJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario:.
        /// </summary>
        public static string lbNombreUsuario {
            get {
                return ResourceManager.GetString("lbNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña:.
        /// </summary>
        public static string lbNuevaContraseña {
            get {
                return ResourceManager.GetString("lbNuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string lbPerfilMenuPrincipal {
            get {
                return ResourceManager.GetString("lbPerfilMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglas de Juego.
        /// </summary>
        public static string lbReglasDeJuego {
            get {
                return ResourceManager.GetString("lbReglasDeJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string lbTituloConfiguracion {
            get {
                return ResourceManager.GetString("lbTituloConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misiones.
        /// </summary>
        public static string lbTituloMisiones {
            get {
                return ResourceManager.GetString("lbTituloMisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Exitoso.
        /// </summary>
        public static string lbTituloRegistro {
            get {
                return ResourceManager.GetString("lbTituloRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienda.
        /// </summary>
        public static string lbTituloTienda {
            get {
                return ResourceManager.GetString("lbTituloTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baraja cambiada adecuadamente.
        /// </summary>
        public static string msbCambioDeBaraja {
            get {
                return ResourceManager.GetString("msbCambioDeBaraja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cerrar el juego?.
        /// </summary>
        public static string msbCerrarJuego {
            get {
                return ResourceManager.GetString("msbCerrarJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cerrar su sesión?.
        /// </summary>
        public static string msbCerrarSesion {
            get {
                return ResourceManager.GetString("msbCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña fue cambiada correctamente..
        /// </summary>
        public static string msbContraseñaCambiada {
            get {
                return ResourceManager.GetString("msbContraseñaCambiada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no pudo ser cambiada..
        /// </summary>
        public static string msbContraseñaNoCambiada {
            get {
                return ResourceManager.GetString("msbContraseñaNoCambiada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas ingresadas no coinciden..
        /// </summary>
        public static string msbContraseñasNoIguales {
            get {
                return ResourceManager.GetString("msbContraseñasNoIguales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información del jugador ha sido actualizada correctamente..
        /// </summary>
        public static string msbDatosCambiados {
            get {
                return ResourceManager.GetString("msbDatosCambiados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han hecho cambios..
        /// </summary>
        public static string msbDatosNoCambiados {
            get {
                return ResourceManager.GetString("msbDatosNoCambiados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La foto del jugador ha sido actualizada correctamente..
        /// </summary>
        public static string msbFotoCambiada {
            get {
                return ResourceManager.GetString("msbFotoCambiada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario que se ha ingresado ya existe..
        /// </summary>
        public static string msbNombreDeUsuarioExistente {
            get {
                return ResourceManager.GetString("msbNombreDeUsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de jugador ha sido actualizado correctamente..
        /// </summary>
        public static string msbNombreUsuarioCambiado {
            get {
                return ResourceManager.GetString("msbNombreUsuarioCambiado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo recuperar la información actual del jugador..
        /// </summary>
        public static string msbNoSePudoRecuperarInformacion {
            get {
                return ResourceManager.GetString("msbNoSePudoRecuperarInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de juego - Clásico .
        /// </summary>
        public static string tabCtrlModoClasico {
            get {
                return ResourceManager.GetString("tabCtrlModoClasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de juego - Ochos locos.
        /// </summary>
        public static string tabCtrlModoOchos {
            get {
                return ResourceManager.GetString("tabCtrlModoOchos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe contener:
        ///Al menos una letra minúscula.
        ///Al menos una letra mayúscula.
        ///Al menos un dígito.
        ///Al menos uno de los caracteres especiales especificados: @,$,!,%,*,?,&amp;,#,.,(),\,-,_
        ///Debe ser tener una longitud de 8 a 16 caracteres..
        /// </summary>
        public static string tbContraseñaInvalida {
            get {
                return ResourceManager.GetString("tbContraseñaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRAZY EIGHTS.
        /// </summary>
        public static string tbCrazyEights {
            get {
                return ResourceManager.GetString("tbCrazyEights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de Juego Clásico
        ///El criterio para jugar cartas es el siguiente:
        ///La carta tiene el mismo número que la carta en el centro. Por ejemplo, un 9 de tréboles se puede jugar si hay un 9 de diamantes en el centro.
        ///La carta tiene el mismo palo que la carta en el centro. Por ejemplo, un As de picas pueda se puede jugar si hay un 7 de picas en el centro.
        ///La carta es un 8. Los 8s se consideran comodines y tienen propiedades especiales, que se explican más adelante. Es decir, un 8 de corazones puede jugarse sin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tbkReglasDeJuegoClasico {
            get {
                return ResourceManager.GetString("tbkReglasDeJuegoClasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de Juego Ochos Locos
        ///
        ///Este es un modo de juego en el que ciertas cartas tienen efectos especiales. Se mantienen todas las reglas discutidas anteriormente, pero las siguientes cartas tendrán efectos especiales sobre los otros jugadores al ser jugadas.
        ///La J salta el turno del siguiente jugador. Es decir, este no podrá jugar ninguna carta ni robar.
        ///La Q o el 10 cambian la dirección del juego. El flujo de turnos será en sentido contrario a las manecillas del reloj hasta que se juegue otra carta como es [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tbkReglasDeJuegoOchos {
            get {
                return ResourceManager.GetString("tbkReglasDeJuegoOchos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha creado la cuenta correctamente..
        /// </summary>
        public static string tbRegistroExitoso {
            get {
                return ResourceManager.GetString("tbRegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baraja cambiada.
        /// </summary>
        public static string ttlCambioDeBaraja {
            get {
                return ResourceManager.GetString("ttlCambioDeBaraja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar juego.
        /// </summary>
        public static string ttlCerrarJuego {
            get {
                return ResourceManager.GetString("ttlCerrarJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre de sesión.
        /// </summary>
        public static string ttlCerrarSesion {
            get {
                return ResourceManager.GetString("ttlCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña cambiada correctamente.
        /// </summary>
        public static string ttlContraseñaCambiada {
            get {
                return ResourceManager.GetString("ttlContraseñaCambiada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo cambiar la contraseña.
        /// </summary>
        public static string ttlContraseñaNoCambiada {
            get {
                return ResourceManager.GetString("ttlContraseñaNoCambiada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string ttlContraseñasNoIguales {
            get {
                return ResourceManager.GetString("ttlContraseñasNoIguales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de jugador cambiados.
        /// </summary>
        public static string ttlDatosCambiados {
            get {
                return ResourceManager.GetString("ttlDatosCambiados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de jugador no cambiados.
        /// </summary>
        public static string ttlDatosNoCambiados {
            get {
                return ResourceManager.GetString("ttlDatosNoCambiados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto de jugador cambiada.
        /// </summary>
        public static string ttlFotoCambiada {
            get {
                return ResourceManager.GetString("ttlFotoCambiada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario ya existe.
        /// </summary>
        public static string ttlNombreDeUsuarioExistente {
            get {
                return ResourceManager.GetString("ttlNombreDeUsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de jugador cambiado.
        /// </summary>
        public static string ttlNombreUsuarioCambiado {
            get {
                return ResourceManager.GetString("ttlNombreUsuarioCambiado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información no recuperada.
        /// </summary>
        public static string ttlNoSePudoRecuperarInformacion {
            get {
                return ResourceManager.GetString("ttlNoSePudoRecuperarInformacion", resourceCulture);
            }
        }
    }
}
