//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyEights.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrazyEights.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar a la sala.
        /// </summary>
        public static string btnAccederComoInvitado {
            get {
                return ResourceManager.GetString("btnAccederComoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartas clásicas.
        /// </summary>
        public static string btnCartasClasicas {
            get {
                return ResourceManager.GetString("btnCartasClasicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartas minimalistas.
        /// </summary>
        public static string btnCartasMinimalistas {
            get {
                return ResourceManager.GetString("btnCartasMinimalistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string btnCerrarSesionDeJuego {
            get {
                return ResourceManager.GetString("btnCerrarSesionDeJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear partida.
        /// </summary>
        public static string btnCrearPartida {
            get {
                return ResourceManager.GetString("btnCrearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontrar partida.
        /// </summary>
        public static string btnEncontrarPartida {
            get {
                return ResourceManager.GetString("btnEncontrarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar cambios.
        /// </summary>
        public static string btnGuardarCambiosDePerfil {
            get {
                return ResourceManager.GetString("btnGuardarCambiosDePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string btnIniciarSesion {
            get {
                return ResourceManager.GetString("btnIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar como Invitado.
        /// </summary>
        public static string btnJugarComoInvitado {
            get {
                return ResourceManager.GetString("btnJugarComoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar Contraseña.
        /// </summary>
        public static string btnRecuperarContraseña {
            get {
                return ResourceManager.GetString("btnRecuperarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string btnRegistrarse {
            get {
                return ResourceManager.GetString("btnRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir del juego.
        /// </summary>
        public static string btnSalirDelJuego {
            get {
                return ResourceManager.GetString("btnSalirDelJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienda.
        /// </summary>
        public static string btnTienda {
            get {
                return ResourceManager.GetString("btnTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string lbAmigosMenuPrincipal {
            get {
                return ResourceManager.GetString("lbAmigosMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ya tienes una cuenta?.
        /// </summary>
        public static string lbApoyoIniciarSesion {
            get {
                return ResourceManager.GetString("lbApoyoIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Te están esperando en una sala?.
        /// </summary>
        public static string lbApoyoJugarComoInvitado {
            get {
                return ResourceManager.GetString("lbApoyoJugarComoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string lbApoyoRecuperarContraseña {
            get {
                return ResourceManager.GetString("lbApoyoRecuperarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tienes una cuenta?.
        /// </summary>
        public static string lbApoyoRegistrarse {
            get {
                return ResourceManager.GetString("lbApoyoRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string lbAyudaMenuPrincipal {
            get {
                return ResourceManager.GetString("lbAyudaMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string lbCerrarVentana {
            get {
                return ResourceManager.GetString("lbCerrarVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de sala:.
        /// </summary>
        public static string lbCodigoSala {
            get {
                return ResourceManager.GetString("lbCodigoSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string lbConfiguracion {
            get {
                return ResourceManager.GetString("lbConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        public static string lbContraseña {
            get {
                return ResourceManager.GetString("lbContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo Electrónico:.
        /// </summary>
        public static string lbCorreoElectronico {
            get {
                return ResourceManager.GetString("lbCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string lbIdioma {
            get {
                return ResourceManager.GetString("lbIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misiones.
        /// </summary>
        public static string lbMisionesMenuPrincipal {
            get {
                return ResourceManager.GetString("lbMisionesMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de jugador.
        /// </summary>
        public static string lbNombreDeJugador {
            get {
                return ResourceManager.GetString("lbNombreDeJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario:.
        /// </summary>
        public static string lbNombreUsuario {
            get {
                return ResourceManager.GetString("lbNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string lbPerfilMenuPrincipal {
            get {
                return ResourceManager.GetString("lbPerfilMenuPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglas de Juego.
        /// </summary>
        public static string lbReglasDeJuego {
            get {
                return ResourceManager.GetString("lbReglasDeJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string lbTituloConfiguracion {
            get {
                return ResourceManager.GetString("lbTituloConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misiones.
        /// </summary>
        public static string lbTituloMisiones {
            get {
                return ResourceManager.GetString("lbTituloMisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Exitoso.
        /// </summary>
        public static string lbTituloRegistro {
            get {
                return ResourceManager.GetString("lbTituloRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienda.
        /// </summary>
        public static string lbTituloTienda {
            get {
                return ResourceManager.GetString("lbTituloTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baraja cambiada adecuadamente.
        /// </summary>
        public static string msbCambioDeBaraja {
            get {
                return ResourceManager.GetString("msbCambioDeBaraja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cerrar el juego?.
        /// </summary>
        public static string msbCerrarJuego {
            get {
                return ResourceManager.GetString("msbCerrarJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea cerrar su sesión?.
        /// </summary>
        public static string msbCerrarSesion {
            get {
                return ResourceManager.GetString("msbCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de juego - Clásico .
        /// </summary>
        public static string tabCtrlModoClasico {
            get {
                return ResourceManager.GetString("tabCtrlModoClasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de juego - Ochos locos.
        /// </summary>
        public static string tabCtrlModoOchos {
            get {
                return ResourceManager.GetString("tabCtrlModoOchos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRAZY EIGHTS.
        /// </summary>
        public static string tbCrazyEights {
            get {
                return ResourceManager.GetString("tbCrazyEights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de Juego Clásico
        ///El criterio para jugar cartas es el siguiente:
        ///La carta tiene el mismo número que la carta en el centro. Por ejemplo, un 9 de tréboles se puede jugar si hay un 9 de diamantes en el centro.
        ///La carta tiene el mismo palo que la carta en el centro. Por ejemplo, un As de picas pueda se puede jugar si hay un 7 de picas en el centro.
        ///La carta es un 8. Los 8s se consideran comodines y tienen propiedades especiales, que se explican más adelante. Es decir, un 8 de corazones puede jugarse sin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tbkReglasDeJuegoClasico {
            get {
                return ResourceManager.GetString("tbkReglasDeJuegoClasico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de Juego Ochos Locos
        ///
        ///Este es un modo de juego en el que ciertas cartas tienen efectos especiales. Se mantienen todas las reglas discutidas anteriormente, pero las siguientes cartas tendrán efectos especiales sobre los otros jugadores al ser jugadas.
        ///La J salta el turno del siguiente jugador. Es decir, este no podrá jugar ninguna carta ni robar.
        ///La Q o el 10 cambian la dirección del juego. El flujo de turnos será en sentido contrario a las manecillas del reloj hasta que se juegue otra carta como es [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tbkReglasDeJuegoOchos {
            get {
                return ResourceManager.GetString("tbkReglasDeJuegoOchos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha creado la cuenta correctamente..
        /// </summary>
        public static string tbRegistroExitoso {
            get {
                return ResourceManager.GetString("tbRegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baraja cambiada.
        /// </summary>
        public static string ttlCambioDeBaraja {
            get {
                return ResourceManager.GetString("ttlCambioDeBaraja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar juego.
        /// </summary>
        public static string ttlCerrarJuego {
            get {
                return ResourceManager.GetString("ttlCerrarJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cierre de sesión.
        /// </summary>
        public static string ttlCerrarSesion {
            get {
                return ResourceManager.GetString("ttlCerrarSesion", resourceCulture);
            }
        }
    }
}
