//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugadores
    {
        public int IDJugador { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<int> monedas { get; set; }
        public string fotoPerfil { get; set; }
        public int IDUsuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
